name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: cd docs; mkdocs build -q
      - run: tar czf kod.tar.gz docs/site/*
      - uses: actions/upload-artifact@v4
        with:
          name: kod-docs-website
          path: kod.tar.gz
          compression-level: 0
          overwrite: true